project_id = "hiuefqcscfmuagdgbefv"

[functions.upload-excel]
verify_jwt = false

[functions.ai-extract]
verify_jwt = false

[functions.stats]
verify_jwt = false

[functions.posts]
verify_jwt = false

[functions.import-whatsapp]
verify_jwt = false

[functions.import-telegram]
verify_jwt = false

[functions.smart-upload]
verify_jwt = false

[functions.chat]
verify_jwt = false